deployment:
  tasks:
    - export DEPLOYPATH=/home/wnohnaxa/public_html/    # Set deployment path

    # Copy static assets to the public_html directory
    - /bin/cp -R public/* $DEPLOYPATH                   # Copy public-facing files like index.php, etc.
    - /bin/cp -R assets $DEPLOYPATH/assets              # Copy assets folder
    - /bin/cp -R css $DEPLOYPATH/css                    # Copy CSS
    - /bin/cp -R fonts $DEPLOYPATH/fonts                # Copy fonts
    - /bin/cp -R img $DEPLOYPATH/img                    # Copy images
    - /bin/cp -R js $DEPLOYPATH/js                      # Copy JS files

    # Now, Laravel-specific tasks (run Composer, migrations, etc.)
    - cd /home/username/public_html/                    # Go to the deployment directory
    - composer install --no-dev --optimize-autoloader --prefer-dist
    - chmod -R 775 storage bootstrap/cache              # Set correct permissions for Laravel's folders
    # - chown -R username:username storage bootstrap/cache
    - php artisan migrate --force                       # Run database migrations
    - php artisan config:cache && php artisan route:cache && php artisan view:clear  # Clear caches
    - php artisan key:generate                          # Generate the Laravel app key
    - php artisan optimize                              # Optimize the Laravel app
